### ISSUE TITLE
DEVELOPER TASK: Setup Django

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/share-story#17]
**Task Description:** Setup Django and other dependencies in Dev Environment

Unit Tasks
- [x] Task : Install Django framework and gunicorn HTTP SERVER.
- [x] Task : Install dj_database and psycopg2 database adapter.
- [x] Task : Install Cloudinary Storage.
- [x] Task : Create Requirements.txt file.
