### ISSUE TITLE
DEVELOPER TASK: Setup Project and App

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/share-story#18]
**Task Description:** Setup basic project code in django and start app.

Unit Tasks
- [x] Task : Start Project 'ShareStory' in django.
- [x] Task : Start 'user' app.
- [x] Task : Add apps to installed apps in settings.py (ShareStory).
- [x] Task: Migrate changes to database.
- [x] Task: Run development server to test.
