### ISSUE TITLE
DEVELOPER TASK: Deploy to Heroku

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/share-story#20]
**Task Description:** Deploy the app to Heroku to ensure errors with deployment and integration with Postgres can be handled early.

Unit Tasks
- [x] Task : Create ShareStory Heroku app.
- [x] Task : Attach Postgres Database.
- [x] Task : Prepare Environment and Settings.py file.
- [x] Task : Makemigrations and Migrate.
- [x] Task : Wire up our static and media storage to Cloudinary
- [x] Task : Create Procfile then commit and push to GitHub.
- [x] Task : Deploy the app using GitHub as a deployment method.
- [x] Task : Change the "DEBUG = True" to false before submitting the final project.
