### ISSUE TITLE
DEVELOPER TASK: Records and Forms Dependencies

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/share-story#22]
**Task Description:** Add crispy forms and summernote to Django to format and style form layouts and inputs.

Unit Tasks
- [x] Task : Install crispy forms.
- [x] Task :  Install Summernote.
- [x] Task : Add apps to settings.py file.
- [x] Task : Update requirements.txt file.
